name: Publish to hex.pm

on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Publish package to hex.pm
        uses: dtraft/action-publish-hex@v1.17.2
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
